apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    meta.helm.sh/release-name: kscp
    meta.helm.sh/release-namespace: secretsplane
  creationTimestamp: "2021-03-04T19:58:28Z"
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  managedFields:
  - apiVersion: admissionregistration.k8s.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:meta.helm.sh/release-name: {}
          f:meta.helm.sh/release-namespace: {}
        f:labels:
          .: {}
          f:app.kubernetes.io/managed-by: {}
      f:webhooks:
        .: {}
        k:{"name":"kscp-injector.kscp.io"}:
          .: {}
          f:admissionReviewVersions: {}
          f:clientConfig:
            .: {}
            f:service:
              .: {}
              f:name: {}
              f:namespace: {}
              f:path: {}
              f:port: {}
          f:failurePolicy: {}
          f:matchPolicy: {}
          f:name: {}
          f:namespaceSelector: {}
          f:objectSelector: {}
          f:reinvocationPolicy: {}
          f:rules: {}
          f:sideEffects: {}
          f:timeoutSeconds: {}
    manager: Go-http-client
    operation: Update
    time: "2021-03-04T19:58:28Z"
  - apiVersion: admissionregistration.k8s.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:webhooks:
        k:{"name":"kscp-injector.kscp.io"}:
          f:clientConfig:
            f:caBundle: {}
    manager: kubectl
    operation: Update
    time: "2021-03-04T19:58:42Z"
  name: kscp-injector
  resourceVersion: "20182801"
  selfLink: /apis/admissionregistration.k8s.io/v1/mutatingwebhookconfigurations/kscp-injector
  uid: 4bd3918a-ce76-4fba-a015-d06ea7441917
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJWakNCL3FBREFnRUNBZ0VBTUFvR0NDcUdTTTQ5QkFNQ01DTXhJVEFmQmdOVkJBTU1HR3N6Y3kxelpYSjIKWlhJdFkyRkFNVFl3TkRBMk1URXdOREFlRncweU1ERXdNekF4TWpNeE5EUmFGdzB6TURFd01qZ3hNak14TkRSYQpNQ014SVRBZkJnTlZCQU1NR0dzemN5MXpaWEoyWlhJdFkyRkFNVFl3TkRBMk1URXdOREJaTUJNR0J5cUdTTTQ5CkFnRUdDQ3FHU000OUF3RUhBMElBQkNsbFNSVU5URWp0aFJsREJSUmhhVXdZNXFMa3FVQStqa0JaNkc2dXZVMVkKZ1VmSHF0SmxvT0ZpemVIY25NSElTbWdwUlMwTXc0S3pXZE02VFJSNGJkS2pJekFoTUE0R0ExVWREd0VCL3dRRQpBd0lDcERBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUFvR0NDcUdTTTQ5QkFNQ0EwY0FNRVFDSUZpVktydFQxU2hTClp0RE5iQ09FZEJhZGwwSkVQaVlRckhWNDdUcVVWRGZpQWlCM1ZUVzhrU2wvdXFUeG13ZFl1Y0Z3R3l1L3NaOUsKdTdUc05ZQUxZSEdXckE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    service:
      name: kscp-injector
      namespace: secretsplane
      path: /mutate
      port: 443
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: kscp-injector.kscp.io
  namespaceSelector: {}
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
