apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
  - args:
    - /kscp/secrets/test
    command:
    - cat
    image: busybox
    imagePullPolicy: Always
    name: test
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: test-token-562vl
      readOnly: true
    - mountPath: /kscp/secrets
      name: kscp-secrets-test
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  initContainers:
  - env:
    - name: PROCESSOR_ADDR
      value: https://kscp-injector.secretsplane.svc
    - name: BIND_test
      value: '{"name": "test", "secrets": "test", "target": "/kscp/secrets/test",
        "template": null}'
    image: registry.tiagoposse.com/kscp-init:dev-1
    imagePullPolicy: Always
    name: kscp-init
    command:
    - tail
    args:
    - -f
    - /dev/null
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /kscp/secrets
      name: kscp-secrets-test
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: test-token-562vl
      readOnly: true
  nodeName: worker1
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: test
  serviceAccountName: test
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: test-token-562vl
    secret:
      defaultMode: 420
      secretName: test-token-562vl
  - emptyDir: {}
    name: kscp-secrets-test
  - emptyDir: {}
    name: kscp-secrets