FROM registry.tiagoposse.com/kscp-base:1.0.0

RUN pip install --pre kopf && pip install jsonpatch

COPY kscp/controller /app/controller
COPY kscp/operator /app/operator

WORKDIR /app/operator
ENTRYPOINT [ "kopf", "run", "--log-format=full", "-v", "main.py", "secrets.py", "secretbindings.py" ]