#!/bin/sh

python3 $(dirname "$0")/kubectl-secrets-plugin.py $@

NAME=""
NAMESPACE=""

curl -XPOST "https://192.168.178.48:6443/api/v1/namespaces/secretsplane/services/https:kscp-injector:443/proxy/readsecret" \
  --data '{
        "auth": '$(kubectl config view --minify | grep password | cut -d ":" -f 2 | xargs)'
        "secret": '$NAME',
        "backend": "vault",
        "namespace": '$NAMESPACE'
    }'