{{- if .Values.injector.enabled }}
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "injector.fullname" . }}
webhooks:
- name: {{ include "injector.fullname" . }}.kscp.io
  matchPolicy: {{ .Values.injector.matchPolicy }}
  failurePolicy: {{ .Values.injector.failurePolicy }}
  {{- if .Values.injector.namespaceSelector }}
  namespaceSelector:
    {{- toYaml .Values.injector.namespaceSelector | nindent 4 }}
  {{ end }}
  clientConfig:
    service:
      namespace: {{ .Release.Namespace }}
      name: {{ include "injector.fullname" . }}
      path: /mutate
      port: {{ .Values.injector.service.port }}
    caBundle: {{ .Values.injector.ca }}
  rules:
  - operations:
      - "CREATE"
    apiGroups:
      - ""
    apiVersions:
      - "v1"
    resources:
      - "pods"
  sideEffects: {{ .Values.injector.sideEffects }}
  timeoutSeconds: {{ .Values.injector.timeoutSeconds | int }}
  reinvocationPolicy: {{ .Values.injector.reinvocationPolicy }}
{{- end }}