
apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
  annotations:
    secrets.kscp.io/inject-bindings: "test"
spec:
  serviceAccountName: test
  containers:
    - name: test
      image: busybox
      command:
        - cat
      args:
        - /kscp/secrets/test