apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: externalsecrets.kscp.io
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: kscp.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              required:
              - values
              - backend
              type: object
              properties:
                values:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
                path:
                  type: string
                backend:
                  type: string
                maxVersions:
                  type: number
                replication:
                  type: string

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: externalsecrets
    # singular name to be used as an alias on the CLI and for display
    singular: externalsecret
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: ExternalSecret
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - es