apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretpolicies.kscp.io
spec:
  group: kscp.io
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1alpha1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            allowed:
              type: array
              items:
                type: string

  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: secretpolicies
    # singular name to be used as an alias on the CLI and for display
    singular: secretpolicy
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: SecretPolicy
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - sp